title: Montaje y Mantenimiento de Equipos
description: Recursos para el módulo Montaje y Mantenimiento de Equipos de SMR
theme: minima

url: https://alexlopezprofe.github.io/MyM/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

markdown: kramdown
